const difficultWords = {
  utilize: "use",
  commence: "start",
  terminate: "end",
  demonstrate: "show",
  approximately: "about",
  purchase: "buy",
  assistance: "help",
  individuals: "people",
  sufficient: "enough",
  obtain: "get",
  endeavor: "try",
  facilitate: "help",
  implement: "carry out",
  modification: "change",
  numerous: "many",
  initial: "first",
  subsequent: "next",
  prior: "before",
  regarding: "about",
  inquire: "ask",
  respond: "answer",
  residence: "home",
  acquire: "get",
  depart: "leave",
  retain: "keep",
  require: "need",
  encounter: "meet",
  perceive: "see",
  construct: "build",
  verify: "check",
  indicate: "show",
  objective: "goal",
  assistance: "help",
  consume: "eat",
  participate: "take part",
  attempt: "try",
  comprehend: "understand",
  observe: "watch",
  select: "choose",
  conclude: "finish",
  initiate: "begin",
  finalize: "complete",
  substantial: "large",
  minimal: "small",
  possess: "have",
  illustrate: "explain",
  assist: "help",
  acquirement: "getting",
  allocate: "give",
  alteration: "change",
  analyze: "study",
  anticipate: "expect",
  apparent: "clear",
  applicable: "relevant",
  ascertain: "find out",
  attain: "reach",
  beneficial: "helpful",
  categorize: "group",
  cease: "stop",
  collaborate: "work together",
  commence: "start",
  compensate: "pay",
  complete: "finish",
  complex: "complicated",
  complicated: "complex",
  comply: "follow",
  compose: "write",
  compute: "calculate",
  concentrate: "focus",
  conclude: "end",
  conduct: "carry out",
  confirm: "check",
  considerable: "large",
  consistent: "steady",
  constitute: "form",
  construct: "build",
  consume: "eat",
  contribute: "give",
  convert: "change",
  convey: "show",
  correspond: "match",
  crucial: "important",
  decline: "decrease",
  define: "explain",
  demonstrate: "show",
  designate: "choose",
  detect: "find",
  determine: "decide",
  develop: "grow",
  differentiate: "tell apart",
  diminish: "reduce",
  discontinue: "stop",
  distribute: "give out",
  eliminate: "remove",
  emphasize: "stress",
  enable: "allow",
  encounter: "meet",
  enhance: "improve",
  ensure: "make sure",
  establish: "set up",
  evaluate: "judge",
  examine: "check",
  exceed: "go beyond",
  expand: "grow",
  experience: "feel",
  explain: "tell",
  extend: "stretch",
  facilitate: "help",
  finalize: "finish",
  formulate: "create",
  function: "work",
  generate: "create",
  illustrate: "show",
  implement: "use",
  imply: "suggest",
  improve: "make better",
  include: "contain",
  indicate: "show",
  initiate: "start",
  inspect: "check",
  integrate: "combine",
  interpret: "explain",
  involve: "include",
  justify: "prove",
  maintain: "keep",
  maximize: "increase",
  minimize: "reduce",
  modify: "change",
  monitor: "watch",
  necessitate: "need",
  notify: "tell",
  obtain: "get",
  operate: "run",
  organize: "arrange",
  participate: "join",
  perform: "do",
  permit: "allow",
  predict: "guess",
  prepare: "get ready",
  present: "show",
  preserve: "keep",
  prevent: "stop",
  process: "handle",
  produce: "make",
  promote: "support",
  propose: "suggest",
  provide: "give",
  publish: "share",
  recognize: "know",
  recommend: "suggest",
  reduce: "cut",
  refer: "point to",
  reflect: "show",
  regulate: "control",
  reinforce: "strengthen",
  relate: "connect",
  release: "let go",
  remove: "take away",
  replace: "swap",
  require: "need",
  resolve: "solve",
  respond: "reply",
  restore: "fix",
  restrict: "limit",
  retain: "keep",
  reveal: "show",
  review: "check",
  revise: "change",
  schedule: "plan",
  select: "choose",
  simplify: "make simple",
  specify: "state",
  structure: "build",
  submit: "send",
  substitute: "replace",
  suggest: "advise",
  summarize: "sum up",
  support: "help",
  sustain: "maintain",
  terminate: "end",
  transform: "change",
  transmit: "send",
  utilize: "use",
  validate: "confirm",
  vary: "change",
  verify: "check"
};

function simplifyWords(sentence) {
  return sentence.split(" ").map(word => {
    const clean = word.toLowerCase().replace(/[^a-z]/g, "");
    return difficultWords[clean] || word;
  }).join(" ");
}

function shortenSentence(sentence) {
  if (sentence.length > 120) {
    return sentence
      .replace(/, and /g, ". ")
      .replace(/ and /g, ". ")
      .replace(/ which /g, ". This ");
  }
  return sentence;
}

export function ruleSimplify(text) {
  const sentences = text.split(/[.!?]/);

  return sentences.map(s => {
    let step1 = simplifyWords(s.trim());
    let step2 = shortenSentence(step1);
    return step2;
  }).join(". ");
}
